### ISSUE TITLE
spec2006 lite wrapper version should be update

### ISSUE THREAD

**Issue by zybzzz** [OpenXiangShan/Deterload#5]
OpenXiangshan/CPU2006LiteWrapper@b1339daf2451bf5a27fa8db2ef098c4e27495062 

This commit resolves a compatibility issue between different spec2006 versions, and spec2006/default.nix in the nix script should be updated to this version

**Comment by xieby1** [comment]
Sure!
https://github.com/xieby1/deterministic_checkpoints/commit/cd73f154687522142b8f58bc17e6a3d80dedf784

**Comment by zybzzz** [comment]
I apologize that the changes I made earlier to CPU2006LiteWrapper produced an error, I've now re-committed the pr to CPU2006LiteWrapper to try and fix the problem and I think I can let you know when I've passed the test on my server.

@xieby1

**Comment by xieby1** [comment]
It's OK. We have reset deterministic_checkpoints, and will merge new committed CPU2006LiteWrapper later.

**Comment by xieby1** [comment]
In order to find errors and bugs as earlier as possible, we will deploy CI (contiguous integration) to automatically run tests.
https://github.com/xieby1/deterministic_checkpoints/issues/6
